In [15]:
import pandas as pd
import numpy as np

# 1.1

In [3]:
df = pd.read_csv("test1.csv")

# delete row with missing value
df_cleaned = df.dropna()

# covariance matrix
cov_matrix = np.cov(df_cleaned, rowvar=False)
cov_matrix

array([[ 2.14851331, -1.38946985, -0.51646635, -0.12932743, -1.05681437],
       [-1.38946985,  1.03534243,  0.3399928 ,  0.19388784,  0.62687597],
       [-0.51646635,  0.3399928 ,  0.94238795,  0.94788729,  0.05178794],
       [-0.12932743,  0.19388784,  0.94788729,  1.11343622, -0.20473118],
       [-1.05681437,  0.62687597,  0.05178794, -0.20473118,  0.59202693]])

In [4]:
ans_cov_matrix = pd.read_csv("testout_1.1.csv")
ans_cov_matrix

x1        x2        x3        x4        x5
0  2.148513 -1.389470 -0.516466 -0.129327 -1.056814
1 -1.389470  1.035342  0.339993  0.193888  0.626876
2 -0.516466  0.339993  0.942388  0.947887  0.051788
3 -0.129327  0.193888  0.947887  1.113436 -0.204731
4 -1.056814  0.626876  0.051788 -0.204731  0.592027

# 1.2

In [5]:
# correlation matrix
corr_matrix = np.corrcoef(df_cleaned, rowvar=False)
corr_matrix

array([[ 1.        , -0.93161849, -0.36295948, -0.08361591, -0.93704179],
       [-0.93161849,  1.        ,  0.34420158,  0.1805826 ,  0.80069826],
       [-0.36295948,  0.34420158,  1.        ,  0.92535668,  0.06933349],
       [-0.08361591,  0.1805826 ,  0.92535668,  1.        , -0.25216254],
       [-0.93704179,  0.80069826,  0.06933349, -0.25216254,  1.        ]])

In [6]:
#  answer
ans_corr_matrix = pd.read_csv("testout_1.2.csv")
ans_corr_matrix

x1        x2        x3        x4        x5
0  1.000000 -0.931618 -0.362959 -0.083616 -0.937042
1 -0.931618  1.000000  0.344202  0.180583  0.800698
2 -0.362959  0.344202  1.000000  0.925357  0.069333
3 -0.083616  0.180583  0.925357  1.000000 -0.252163
4 -0.937042  0.800698  0.069333 -0.252163  1.000000

## 1.3

In [7]:
# pairwise missing value handling
# covariance matrix
cov = df.cov()
cov

x1        x2        x3        x4        x5
x1  1.173986 -0.629631 -0.278932 -0.081448 -0.735140
x2 -0.629631  1.318197  0.018090  0.446047  0.139309
x3 -0.278932  0.018090  0.918102  0.360836  0.258613
x4 -0.081448  0.446047  0.360836  0.894764 -0.235190
x5 -0.735140  0.139309  0.258613 -0.235190  0.522607

In [8]:
ans_cov = pd.read_csv("testout_1.3.csv")
ans_cov

x1        x2        x3        x4        x5
0  1.173986 -0.629631 -0.278932 -0.081448 -0.735140
1 -0.629631  1.318197  0.018090  0.446047  0.139309
2 -0.278932  0.018090  0.918102  0.360836  0.258613
3 -0.081448  0.446047  0.360836  0.894764 -0.235190
4 -0.735140  0.139309  0.258613 -0.235190  0.522607

# 1.4

In [9]:
# correlation matrix pairwise for missing value handling
corr = df.corr()
corr

x1        x2        x3        x4        x5
x1  1.000000 -0.483199 -0.241787 -0.067767 -0.714761
x2 -0.483199  1.000000  0.015446  0.405660  0.178286
x3 -0.241787  0.015446  1.000000  0.488250  0.336248
x4 -0.067767  0.405660  0.488250  1.000000 -0.322136
x5 -0.714761  0.178286  0.336248 -0.322136  1.000000

In [10]:
ans_corr = pd.read_csv("testout_1.4.csv")
ans_corr

x1        x2        x3        x4        x5
0  1.000000 -0.483199 -0.241787 -0.067767 -0.714761
1 -0.483199  1.000000  0.015446  0.405660  0.178286
2 -0.241787  0.015446  1.000000  0.488250  0.336248
3 -0.067767  0.405660  0.488250  1.000000 -0.322136
4 -0.714761  0.178286  0.336248 -0.322136  1.000000

# 2.1 

In [44]:
# EW covariance matrix, lambda = 0.97
def ew_cov(mat, lam=0.97):
    m, n = mat.shape
    # get the weight
    w = np.array([(1 - lam) * (lam ** (m - 1 - i)) for i in range(m)])
    w = w / sum(w)
    # get diag(w)
    W = np.diag(w)
    # calculate mu with mu = Rw
    mu = np.dot(mat.T, w)
    # calculate ew cov with EW = RWR^T - mumu^T
    ew_cov = mat.T @ W @ mat - np.outer(mu, mu)
    return ew_cov
df = pd.read_csv("test2.csv")
mat = df.values
ew_cov_matrix = ew_cov(mat)
ew_cov_matrix
    


array([[ 0.84863034,  0.12004255,  0.17914903,  0.08394191,  0.05543194],
       [ 0.12004255,  1.07958909,  0.02468223,  0.11512402, -0.42961143],
       [ 0.17914903,  0.02468223,  0.73645659,  0.13376497,  0.06903314],
       [ 0.08394191,  0.11512402,  0.13376497,  0.86793247,  0.11278806],
       [ 0.05543194, -0.42961143,  0.06903314,  0.11278806,  1.13792715]])

In [13]:
ans_ew_cov = pd.read_csv("testout_2.1.csv")
ans_ew_cov

x1        x2        x3        x4        x5
0  0.848630  0.120043  0.179149  0.083942  0.055432
1  0.120043  1.079589  0.024682  0.115124 -0.429611
2  0.179149  0.024682  0.736457  0.133765  0.069033
3  0.083942  0.115124  0.133765  0.867932  0.112788
4  0.055432 -0.429611  0.069033  0.112788  1.137927

In [32]:
np.diag(ew_cov_matrix)

array([0.84863034, 1.07958909, 0.73645659, 0.86793247, 1.13792715])

## 2.2

In [27]:
# ew correlation matrix, lambda = 0.94
def ew_corr(mat, lam=0.94):
    cov = ew_cov(mat, lam)
    d = np.sqrt(np.diag(cov))
    corr = cov / np.outer(d, d)
    return corr
df = pd.read_csv("test2.csv")
mat = df.values
ew_corr_matrix = ew_corr(mat)
ew_corr_matrix

array([[ 1.        ,  0.08478716,  0.19010008,  0.12904533,  0.07070604],
       [ 0.08478716,  1.        , -0.07743167,  0.20222796, -0.44254624],
       [ 0.19010008, -0.07743167,  1.        ,  0.19826708,  0.10209287],
       [ 0.12904533,  0.20222796,  0.19826708,  1.        ,  0.11954092],
       [ 0.07070604, -0.44254624,  0.10209287,  0.11954092,  1.        ]])

In [25]:
ans_ew_cov = pd.read_csv("testout_2.2.csv")
ans_ew_cov

x1        x2        x3        x4        x5
0  1.000000  0.084787  0.190100  0.129045  0.070706
1  0.084787  1.000000 -0.077432  0.202228 -0.442546
2  0.190100 -0.077432  1.000000  0.198267  0.102093
3  0.129045  0.202228  0.198267  1.000000  0.119541
4  0.070706 -0.442546  0.102093  0.119541  1.000000

## 2.3

In [33]:
# covariance with ew variance(lambda = 0.97) and ew correlation (lambda = 0.94)
ew_var = np.diag(ew_cov(mat, lam=0.97))
ew_corr_matrix = ew_corr(mat, lam=0.94)
ew_cov_matrix = np.outer(np.sqrt(ew_var), np.sqrt(ew_var)) * ew_corr_matrix
ew_cov_matrix

array([[ 0.84863034,  0.08115562,  0.15028483,  0.1107502 ,  0.06948211],
       [ 0.08115562,  1.07958909, -0.06904329,  0.19575525, -0.49050691],
       [ 0.15028483, -0.06904329,  0.73645659,  0.15851383,  0.0934601 ],
       [ 0.1107502 ,  0.19575525,  0.15851383,  0.86793247,  0.11880009],
       [ 0.06948211, -0.49050691,  0.0934601 ,  0.11880009,  1.13792715]])

In [34]:
ans_cov = pd.read_csv("testout_2.3.csv")
ans_cov

x1        x2        x3        x4        x5
0  0.848630  0.081156  0.150285  0.110750  0.069482
1  0.081156  1.079589 -0.069043  0.195755 -0.490507
2  0.150285 -0.069043  0.736457  0.158514  0.093460
3  0.110750  0.195755  0.158514  0.867932  0.118800
4  0.069482 -0.490507  0.093460  0.118800  1.137927

## 3.1

In [45]:
# near psd matrix
def near_psd_cov(A, epsilon = 0):
    # get correlation matrix
    d = np.sqrt(np.diag(A))
    corr = A / np.outer(d, d)
    eig_vals, eig_vecs = np.linalg.eig(corr)
    eig_vals[eig_vals < epsilon] = epsilon
    corr_psd = (eig_vecs @ np.diag(eig_vals) @ eig_vecs.T)
    corr_psd = corr_psd / np.outer(np.sqrt(np.diag(corr_psd)), np.sqrt(np.diag(corr_psd)))
    near_A = np.outer(d, d) * corr_psd
    return near_A
df = pd.read_csv("testout_1.3.csv")
mat = df.values
near_psd_matrix = near_psd_cov(mat)
near_psd_matrix

array([[ 1.17398583, -0.61798867, -0.284559  , -0.06515152, -0.68828687],
       [-0.61798867,  1.3181973 ,  0.01709196,  0.44569555,  0.13917594],
       [-0.284559  ,  0.01709196,  0.91810185,  0.35414666,  0.24605561],
       [-0.06515152,  0.44569555,  0.35414666,  0.89476398, -0.21871734],
       [-0.68828687,  0.13917594,  0.24605561, -0.21871734,  0.52260731]])

In [38]:
ans = pd.read_csv("testout_3.1.csv")
ans

x1        x2        x3        x4        x5
0  1.173986 -0.617989 -0.284559 -0.065152 -0.688287
1 -0.617989  1.318197  0.017092  0.445696  0.139176
2 -0.284559  0.017092  0.918102  0.354147  0.246056
3 -0.065152  0.445696  0.354147  0.894764 -0.218717
4 -0.688287  0.139176  0.246056 -0.218717  0.522607

In [39]:
np.linalg.eigvals(ans)

array([2.23908420e+00, 9.88575238e-17, 2.60303538e-01, 1.27988093e+00,
       1.04838760e+00])

## 3.2

In [46]:
def near_psd_corr(A, epsilon = 0):
    eig_vals, eig_vecs = np.linalg.eig(A)
    eig_vals[eig_vals < epsilon] = epsilon
    corr_psd = (eig_vecs @ np.diag(eig_vals) @ eig_vecs.T)
    corr_psd = corr_psd / np.outer(np.sqrt(np.diag(corr_psd)), np.sqrt(np.diag(corr_psd)))
    return corr_psd
df = pd.read_csv("testout_1.4.csv")
mat = df.values
near_psd_corr_matrix = near_psd_corr(mat)
near_psd_corr_matrix

array([[ 1.        , -0.48319932, -0.24178663, -0.06776693, -0.71476123],
       [-0.48319932,  1.        ,  0.01544631,  0.40565982,  0.17828625],
       [-0.24178663,  0.01544631,  1.        ,  0.48824985,  0.33624763],
       [-0.06776693,  0.40565982,  0.48824985,  1.        , -0.32213624],
       [-0.71476123,  0.17828625,  0.33624763, -0.32213624,  1.        ]])

In [47]:
ans = pd.read_csv("testout_3.2.csv")
ans

x1        x2        x3        x4        x5
0  1.000000 -0.483199 -0.241787 -0.067767 -0.714761
1 -0.483199  1.000000  0.015446  0.405660  0.178286
2 -0.241787  0.015446  1.000000  0.488250  0.336248
3 -0.067767  0.405660  0.488250  1.000000 -0.322136
4 -0.714761  0.178286  0.336248 -0.322136  1.000000

## 3.3

In [51]:
# Higham coverance matrix
def higham_corr(A, max_iter=100, tol=1e-6):
    n = A.shape[0]
    # symmetric
    A = (A + A.T) / 2
    X = A.copy()
    Y = np.zeros_like(A)
    for i in range(max_iter):
        R = X - Y
        eig_vals, eig_vecs = np.linalg.eig(R)
        eig_vals[eig_vals < 0] = 0
        X_new = eig_vecs @ np.diag(eig_vals) @ eig_vecs.T
        Y = X_new - R
        X_new[np.diag_indices(n)] = 1
        if np.linalg.norm(X_new - X, ord='fro') < tol:
            break
        X = X_new
    return X
def higham_cov(A, max_iter=100, tol=1e-6):
    # get correlation matrix
    d = np.sqrt(np.diag(A))
    corr = A / np.outer(d, d)
    corr_psd = higham_corr(corr, max_iter, tol)
    near_A = np.outer(d, d) * corr_psd
    return near_A
df = pd.read_csv("testout_1.3.csv")
mat = df.values
higham_matrix = higham_cov(mat)
higham_matrix

array([[ 1.17398583, -0.62387011, -0.29433458, -0.05767744, -0.69388853],
       [-0.62387011,  1.3181973 ,  0.0164492 ,  0.44857878,  0.14370277],
       [-0.29433458,  0.0164492 ,  0.91810185,  0.35406697,  0.24686664],
       [-0.05767744,  0.44857878,  0.35406697,  0.89476398, -0.21706244],
       [-0.69388853,  0.14370277,  0.24686664, -0.21706244,  0.52260731]])

In [52]:
ans = pd.read_csv("testout_3.3.csv")
ans

x1        x2        x3        x4        x5
0  1.173986 -0.623870 -0.294335 -0.057677 -0.693888
1 -0.623870  1.318197  0.016449  0.448579  0.143703
2 -0.294335  0.016449  0.918102  0.354067  0.246866
3 -0.057677  0.448579  0.354067  0.894764 -0.217062
4 -0.693888  0.143703  0.246866 -0.217062  0.522607

## 3.4

In [53]:
df = pd.read_csv("testout_1.4.csv")
mat = df.values
higham_corr_matrix = higham_corr(mat)
higham_corr_matrix

array([[ 1.        , -0.48319932, -0.24178663, -0.06776693, -0.71476123],
       [-0.48319932,  1.        ,  0.01544631,  0.40565982,  0.17828625],
       [-0.24178663,  0.01544631,  1.        ,  0.48824985,  0.33624763],
       [-0.06776693,  0.40565982,  0.48824985,  1.        , -0.32213624],
       [-0.71476123,  0.17828625,  0.33624763, -0.32213624,  1.        ]])

In [55]:
ans = pd.read_csv("testout_3.4.csv")
ans

x1        x2        x3        x4        x5
0  1.000000 -0.483199 -0.241787 -0.067767 -0.714761
1 -0.483199  1.000000  0.015446  0.405660  0.178286
2 -0.241787  0.015446  1.000000  0.488250  0.336248
3 -0.067767  0.405660  0.488250  1.000000 -0.322136
4 -0.714761  0.178286  0.336248 -0.322136  1.000000

## 4.1

In [71]:
df = pd.read_csv("testout_3.1.csv")
mat = df.values
chol_psd = np.linalg.cholesky(mat)
pd.DataFrame(chol_psd)

0         1         2         3             4
0  1.083506  0.000000  0.000000  0.000000  0.000000e+00
1 -0.570360  0.996437  0.000000  0.000000  0.000000e+00
2 -0.262628 -0.133175  0.911807  0.000000  0.000000e+00
3 -0.060130  0.412871  0.431384  0.731160  0.000000e+00
4 -0.635240 -0.223938  0.054179 -0.256892  1.053671e-08

In [57]:
ans = pd.read_csv("testout_4.1.csv")
ans

x1        x2        x3        x4            x5
0  1.083506  0.000000  0.000000  0.000000  0.000000e+00
1 -0.570360  0.996437  0.000000  0.000000  0.000000e+00
2 -0.262628 -0.133175  0.911807  0.000000  0.000000e+00
3 -0.060130  0.412871  0.431384  0.731160  0.000000e+00
4 -0.635240 -0.223938  0.054179 -0.256892  1.053671e-08

## 6.1

In [91]:
df = pd.read_csv("test6.csv")
df.set_index('Date', inplace=True)
df.index = pd.to_datetime(df.index)
arithm_ret = df.pct_change().dropna().reset_index()
arithm_ret

Date       SPY      AAPL      MSFT      AMZN      NVDA     GOOGL  \
0   2022-09-02 -0.010544 -0.013611 -0.016667 -0.002425 -0.020808 -0.017223   
1   2022-09-06 -0.003773 -0.008215 -0.010974 -0.010980 -0.013336 -0.009643   
2   2022-09-07  0.017965  0.009254  0.019111  0.026723  0.018795  0.024717   
3   2022-09-08  0.006536 -0.009618  0.001666  0.002626  0.020126 -0.009776   
4   2022-09-09  0.015535  0.018840  0.022977  0.026575  0.028377  0.020945   
..         ...       ...       ...       ...       ...       ...       ...   
260 2023-09-18  0.000586  0.016913 -0.003513 -0.002920  0.001503  0.005895   
261 2023-09-19 -0.002074  0.006181 -0.001246 -0.016788 -0.010144 -0.001230   
262 2023-09-20 -0.009193 -0.019992 -0.023977 -0.017002 -0.029435 -0.031150   
263 2023-09-21 -0.016528 -0.008889 -0.003866 -0.044053 -0.028931 -0.024675   
264 2023-09-22 -0.002249  0.004945 -0.007887 -0.001624  0.014457 -0.001457   

         TSLA      GOOG     BRK-B  ...        CI       ETN       SLB  \
0   -0.025076 -0.016915 -0.016854  ... -0.001180 -0.010593  0.033107   
1    0.015581 -0.011042 -0.003890  ... -0.004641  0.008449 -0.014118   
2    0.033817  0.027912  0.016089  ...  0.016652  0.020295 -0.008030   
3    0.019598 -0.009595  0.008184  ...  0.002448  0.013945  0.029951   
4    0.036023  0.021568  0.008576  ...  0.007327  0.017244  0.038774   
..        ...       ...       ...  ...       ...       ...       ...   
260 -0.033201  0.004772  0.006986  ...  0.007485  0.006938  0.010399   
261  0.004599 -0.000936  0.000135  ... -0.002453 -0.013644 -0.012743   
262 -0.014672 -0.030541 -0.009879  ...  0.009450 -0.006986 -0.010591   
263 -0.026239 -0.023999 -0.009651  ...  0.012216 -0.018635 -0.016223   
264 -0.042315 -0.000837 -0.008588  ... -0.004814  0.009542  0.003740   

          PGR      SCHW      LRCX       ZTS         C       BSX       AMT  
0   -0.010428 -0.019242 -0.004236 -0.015244  0.001846 -0.012198 -0.026355  
1    0.000572  0.001848 -0.008019 -0.000892 -0.012695 -0.002717  0.013275  
2    0.038537  0.018731  0.012279  0.022698  0.008503  0.026994  0.020930  
3    0.015880  0.019083  0.016574 -0.011908  0.026116  0.029901  0.008362  
4   -0.004179  0.018863  0.026460  0.036721  0.015431  0.005385 -0.000306  
..        ...       ...       ...       ...       ...       ...       ...  
260  0.013118 -0.006183  0.020125 -0.003329 -0.001639  0.001890 -0.003386  
261  0.013589 -0.002247 -0.016519  0.012970  0.000938  0.000566 -0.012087  
262  0.001544 -0.018361 -0.010062 -0.002748 -0.008903  0.020177  0.000282  
263 -0.002032 -0.011646 -0.013686 -0.026725 -0.013948 -0.002403 -0.045601  
264  0.006039 -0.015354  0.014286  0.000283 -0.018940 -0.006856 -0.018368  

[265 rows x 102 columns]

In [88]:
ans = pd.read_csv("testout6_1.csv")
ans

Date       SPY      AAPL      MSFT      AMZN      NVDA     GOOGL  \
0    2022-09-02 -0.010544 -0.013611 -0.016667 -0.002425 -0.020808 -0.017223   
1    2022-09-06 -0.003773 -0.008215 -0.010974 -0.010980 -0.013336 -0.009643   
2    2022-09-07  0.017965  0.009254  0.019111  0.026723  0.018795  0.024717   
3    2022-09-08  0.006536 -0.009618  0.001666  0.002626  0.020126 -0.009776   
4    2022-09-09  0.015535  0.018840  0.022977  0.026575  0.028377  0.020945   
..          ...       ...       ...       ...       ...       ...       ...   
260  2023-09-18  0.000586  0.016913 -0.003513 -0.002920  0.001503  0.005895   
261  2023-09-19 -0.002074  0.006181 -0.001246 -0.016788 -0.010144 -0.001230   
262  2023-09-20 -0.009193 -0.019992 -0.023977 -0.017002 -0.029435 -0.031150   
263  2023-09-21 -0.016528 -0.008889 -0.003866 -0.044053 -0.028931 -0.024675   
264  2023-09-22 -0.002249  0.004945 -0.007887 -0.001624  0.014457 -0.001457   

         TSLA      GOOG     BRK-B  ...        CI       ETN       SLB  \
0   -0.025076 -0.016915 -0.016854  ... -0.001180 -0.010593  0.033107   
1    0.015581 -0.011042 -0.003890  ... -0.004641  0.008449 -0.014118   
2    0.033817  0.027912  0.016089  ...  0.016652  0.020295 -0.008030   
3    0.019598 -0.009595  0.008184  ...  0.002448  0.013945  0.029951   
4    0.036023  0.021568  0.008576  ...  0.007327  0.017244  0.038774   
..        ...       ...       ...  ...       ...       ...       ...   
260 -0.033201  0.004772  0.006986  ...  0.007485  0.006938  0.010399   
261  0.004599 -0.000936  0.000135  ... -0.002453 -0.013644 -0.012743   
262 -0.014672 -0.030541 -0.009879  ...  0.009450 -0.006986 -0.010591   
263 -0.026239 -0.023999 -0.009651  ...  0.012216 -0.018635 -0.016223   
264 -0.042315 -0.000837 -0.008588  ... -0.004814  0.009542  0.003740   

          PGR      SCHW      LRCX       ZTS         C       BSX       AMT  
0   -0.010428 -0.019242 -0.004236 -0.015244  0.001846 -0.012198 -0.026355  
1    0.000572  0.001848 -0.008019 -0.000892 -0.012695 -0.002717  0.013275  
2    0.038537  0.018731  0.012279  0.022698  0.008503  0.026994  0.020930  
3    0.015880  0.019083  0.016574 -0.011908  0.026116  0.029901  0.008362  
4   -0.004179  0.018863  0.026460  0.036721  0.015431  0.005385 -0.000306  
..        ...       ...       ...       ...       ...       ...       ...  
260  0.013118 -0.006183  0.020125 -0.003329 -0.001639  0.001890 -0.003386  
261  0.013589 -0.002247 -0.016519  0.012970  0.000938  0.000566 -0.012087  
262  0.001544 -0.018361 -0.010062 -0.002748 -0.008903  0.020177  0.000282  
263 -0.002032 -0.011646 -0.013686 -0.026725 -0.013948 -0.002403 -0.045601  
264  0.006039 -0.015354  0.014286  0.000283 -0.018940 -0.006856 -0.018368  

[265 rows x 102 columns]

## 6.2

In [ ]:
log_ret = np.log(df / df.shift(1)).dropna().reset_index()
log_ret

Date       SPY      AAPL      MSFT      AMZN      NVDA     GOOGL  \
0   2022-09-02 -0.010600 -0.013705 -0.016807 -0.002428 -0.021027 -0.017373   
1   2022-09-06 -0.003780 -0.008249 -0.011035 -0.011040 -0.013426 -0.009690   
2   2022-09-07  0.017806  0.009211  0.018931  0.026372  0.018621  0.024416   
3   2022-09-08  0.006515 -0.009664  0.001665  0.002623  0.019926 -0.009824   
4   2022-09-09  0.015416  0.018664  0.022717  0.026228  0.027982  0.020729   
..         ...       ...       ...       ...       ...       ...       ...   
260 2023-09-18  0.000586  0.016772 -0.003519 -0.002925  0.001502  0.005878   
261 2023-09-19 -0.002076  0.006162 -0.001247 -0.016931 -0.010196 -0.001231   
262 2023-09-20 -0.009236 -0.020195 -0.024269 -0.017148 -0.029877 -0.031646   
263 2023-09-21 -0.016666 -0.008929 -0.003873 -0.045053 -0.029357 -0.024984   
264 2023-09-22 -0.002251  0.004932 -0.007918 -0.001625  0.014354 -0.001458   

         TSLA      GOOG     BRK-B  ...        CI       ETN       SLB  \
0   -0.025396 -0.017060 -0.016997  ... -0.001181 -0.010650  0.032571   
1    0.015460 -0.011103 -0.003897  ... -0.004652  0.008413 -0.014219   
2    0.033258  0.027530  0.015961  ...  0.016515  0.020091 -0.008062   
3    0.019409 -0.009641  0.008151  ...  0.002445  0.013849  0.029512   
4    0.035389  0.021339  0.008540  ...  0.007300  0.017097  0.038041   
..        ...       ...       ...  ...       ...       ...       ...   
260 -0.033765  0.004761  0.006962  ...  0.007457  0.006914  0.010346   
261  0.004588 -0.000936  0.000135  ... -0.002456 -0.013738 -0.012825   
262 -0.014780 -0.031017 -0.009928  ...  0.009406 -0.007010 -0.010647   
263 -0.026589 -0.024291 -0.009697  ...  0.012142 -0.018811 -0.016357   
264 -0.043237 -0.000838 -0.008625  ... -0.004825  0.009497  0.003733   

          PGR      SCHW      LRCX       ZTS         C       BSX       AMT  
0   -0.010483 -0.019429 -0.004245 -0.015361  0.001844 -0.012273 -0.026708  
1    0.000572  0.001846 -0.008052 -0.000892 -0.012776 -0.002720  0.013187  
2    0.037813  0.018558  0.012204  0.022445  0.008467  0.026636  0.020714  
3    0.015756  0.018904  0.016438 -0.011979  0.025780  0.029463  0.008327  
4   -0.004188  0.018687  0.026116  0.036063  0.015313  0.005371 -0.000306  
..        ...       ...       ...       ...       ...       ...       ...  
260  0.013033 -0.006203  0.019925 -0.003334 -0.001640  0.001889 -0.003392  
261  0.013497 -0.002249 -0.016656  0.012886  0.000938  0.000566 -0.012161  
262  0.001543 -0.018532 -0.010113 -0.002751 -0.008943  0.019976  0.000282  
263 -0.002035 -0.011715 -0.013781 -0.027088 -0.014046 -0.002406 -0.046673  
264  0.006021 -0.015473  0.014185  0.000283 -0.019122 -0.006879 -0.018538  

[265 rows x 102 columns]

In [90]:
ans = pd.read_csv("testout6_2.csv")
ans

Date       SPY      AAPL      MSFT      AMZN      NVDA     GOOGL  \
0    2022-09-02 -0.010600 -0.013705 -0.016807 -0.002428 -0.021027 -0.017373   
1    2022-09-06 -0.003780 -0.008249 -0.011035 -0.011040 -0.013426 -0.009690   
2    2022-09-07  0.017806  0.009211  0.018931  0.026372  0.018621  0.024416   
3    2022-09-08  0.006515 -0.009664  0.001665  0.002623  0.019926 -0.009824   
4    2022-09-09  0.015416  0.018664  0.022717  0.026228  0.027982  0.020729   
..          ...       ...       ...       ...       ...       ...       ...   
260  2023-09-18  0.000586  0.016772 -0.003519 -0.002925  0.001502  0.005878   
261  2023-09-19 -0.002076  0.006162 -0.001247 -0.016931 -0.010196 -0.001231   
262  2023-09-20 -0.009236 -0.020195 -0.024269 -0.017148 -0.029877 -0.031646   
263  2023-09-21 -0.016666 -0.008929 -0.003873 -0.045053 -0.029357 -0.024984   
264  2023-09-22 -0.002251  0.004932 -0.007918 -0.001625  0.014354 -0.001458   

         TSLA      GOOG     BRK-B  ...        CI       ETN       SLB  \
0   -0.025396 -0.017060 -0.016997  ... -0.001181 -0.010650  0.032571   
1    0.015460 -0.011103 -0.003897  ... -0.004652  0.008413 -0.014219   
2    0.033258  0.027530  0.015961  ...  0.016515  0.020091 -0.008062   
3    0.019409 -0.009641  0.008151  ...  0.002445  0.013849  0.029512   
4    0.035389  0.021339  0.008540  ...  0.007300  0.017097  0.038041   
..        ...       ...       ...  ...       ...       ...       ...   
260 -0.033765  0.004761  0.006962  ...  0.007457  0.006914  0.010346   
261  0.004588 -0.000936  0.000135  ... -0.002456 -0.013738 -0.012825   
262 -0.014780 -0.031017 -0.009928  ...  0.009406 -0.007010 -0.010647   
263 -0.026589 -0.024291 -0.009697  ...  0.012142 -0.018811 -0.016357   
264 -0.043237 -0.000838 -0.008625  ... -0.004825  0.009497  0.003733   

          PGR      SCHW      LRCX       ZTS         C       BSX       AMT  
0   -0.010483 -0.019429 -0.004245 -0.015361  0.001844 -0.012273 -0.026708  
1    0.000572  0.001846 -0.008052 -0.000892 -0.012776 -0.002720  0.013187  
2    0.037813  0.018558  0.012204  0.022445  0.008467  0.026636  0.020714  
3    0.015756  0.018904  0.016438 -0.011979  0.025780  0.029463  0.008327  
4   -0.004188  0.018687  0.026116  0.036063  0.015313  0.005371 -0.000306  
..        ...       ...       ...       ...       ...       ...       ...  
260  0.013033 -0.006203  0.019925 -0.003334 -0.001640  0.001889 -0.003392  
261  0.013497 -0.002249 -0.016656  0.012886  0.000938  0.000566 -0.012161  
262  0.001543 -0.018532 -0.010113 -0.002751 -0.008943  0.019976  0.000282  
263 -0.002035 -0.011715 -0.013781 -0.027088 -0.014046 -0.002406 -0.046673  
264  0.006021 -0.015473  0.014185  0.000283 -0.019122 -0.006879 -0.018538  

[265 rows x 102 columns]